name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest

      - name: SSH and deploy on Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_VM_IP}}
          username: ${{ secrets.ORACLE_VM_USERNAME }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          script: |
            docker stop ${{ secrets.DOCKERHUB_REPO }} || true
            docker rm ${{ secrets.DOCKERHUB_REPO }} || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            echo "${{ secrets.ENV_FILE }}" > .env
            docker run -d --name ${{ secrets.DOCKERHUB_REPO }} -p 80:8000 \
            --env-file .env \
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            rm .env